-- CreateTable
CREATE TABLE `house` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `room` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    `bath` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    `type` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `price` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `desc` VARCHAR(250) NOT NULL DEFAULT '',
    `wallet` VARCHAR(100) NOT NULL DEFAULT '',
    `img` VARCHAR(200) NOT NULL DEFAULT '',
    `ens` VARCHAR(100) NOT NULL DEFAULT '',

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
